### ISSUE TITLE
Add a "simple-build" script for linux

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#381]
Add a script that:

- install's dependencies on supported platforms
- installs conan and builds inexor in `/opt/inexor` for Alpha releases
- add instructions (that you can copy) to run Inexor

Add a respective wiki page that:
- discusses on prebuild packages, where they can be found, how one can help us to prebuild them
- add's copy-to-paste instructions for the simple build script 
- add's instructions with *pictures* to the Windows part
- add's a note on OS X
- links to the old build page for more detailed information

**Comment by Fohlen** [comment]
This will be deprecated by the rolling release system, see #405

**Comment by Croydon** [comment]
How can a binary distribution solve an easy building issue?

**Comment by aschaeffer** [comment]
True. The rolling release distribution system is targeted towards end users, beta testers and early adopters. But as a first time contributor you would be glad to have a script which prepares a working development environment which installs conan, npm, gcc and so on. Maybe we should reopen and adjust the issue description?

**Comment by Fohlen** [comment]
This could be used by providing two seperate `snap` packages

- one based on the `nvm/node` plugin which just installs the game
- one on the `python` plugin, additionally specifying adding our compiler infrastructure. Use `conan` as the pip dependency, and there you go.

**Comment by Fohlen** [comment]
A snapcraft-yaml could look like this

```yaml
name: inexor
summary: "Fast classic gameplay crossed with modern technology."
version: "0.9.0"
description: |
    Cooperatively create levels with the built-in map editor.
    Master manic multiplayer matches.
    Made with love, not money.
    It's free and open source.
grade: stable
parts:
  inexor-flex:
    filesets:
      desktop: [ ~/share/applications inexor.desktop ]
      icon: [ ~share/applications inexor.ico ]
    source: https://github.com/inexorgame/inexor-flex.git
    source-tag: 0.9.0
    plugin: nodejs
    node-engine: 8.4.0
    npm-run: npm i -g
```
