### ISSUE TITLE
At startup load the instance tree configuration from TOML file

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-core#424]
Currently, during starting an `Inexor Core` instance the corresponding `Inexor Tree` gets populated with the default values from the `RPCTreeData-inexor.proto` file. Additionally we should load the tree configuration from a TOML file. The configuration values have precedence over the default values.

The configuration file is located in the profile folder, so you can have individual configurations for each instance per profile.

### Example

_{configFolder}/profiles/client/31417.toml_
```TOML
wallclock = 1
wallclock24 = 1
wallclocksecs = 1

[rendering.screen]
fullscreen = 1
```

_{configFolder}/profiles/devenv/31417.toml_
```TOML
# Make visual that we're using the devenv profile
crosshairsize = 80

# Windowed mode makes debugging more effective
[rendering.screen]
fullscreen = 0
scr_w = 800
scr_h = 600
```

### Tasks

- [x] Load instance configuration from TOML file
- [x] Populate instance tree

### Follow up tasks

At a later point we need to extend the proto file with a new option `overwrite`. The default value of a tree node can be overwritten by configuration files. Not every tree node should be configurable.
